export const Android = "10.0.2.2";
export const backend_host = "192.168.56.1";
export const Geny = "10.0.3.2";
export const host = Geny; // Sửa IP ở đây
export const GET_ALL_QUOTAIOTIONS = `http://${host}:5000/api/standard-quotations/`;
export const REGISTER = `http://${host}:5000/api/accounts/register`;
export const LOGIN = `http://${host}:5000/api/accounts/login`;
export const API_BLOG = `http://${host}:5000/api/blogs`;
export const API_NEWS = `http://${host}:5000/api/news`;
export const API_PROJECT = `http://${host}:5000/api/project`;
